### ISSUE TITLE
A revision is created even when there is no change to the *.charm

### ISSUE THREAD

**Issue by sed-i** [canonical/charming-actions#35]
This is probably a lot to ask for, but:
A revision is created when all I changed was tests, which are not included in the charm.
Parsing `charmcraft.yaml` and re-implementing charmcraft's logic is probably too much to ask for though.
Unless this could be turned into a bot with commands..? In that case we'd use commands such as `$$merge$$` and `$$merge-no-upload$$`.

**Comment by simskij** [comment]
> Unless this could be turned into a bot with commands

While an interesting project, this is not something I'm too keen on adding. 😅 

> A revision is created when all I changed was tests, which are not included in the charm

This part we need to sort out I feel, and it's of quite high priority as well. There are two major cases I think we need to sort out as part of this:

### 1. Changes to the charm itself

I think a reasonable approach would be to check the git diff for the current commit and the previous one and look for changes to the following paths:

 - `/src/*` and `/src/**/*`
 - `/lib/*` and `/lib/**/*`, or to
 - `metadata.yaml`
 - `charmcraft.yaml`
 - `config.yaml`
 - `actions.yaml`
 - `requirements.txt`

and if so, release a new charm revision.

### 2. Charm resources have changed

Check whether any resource revisions have been pushed since the last charm revision was published and if so, release a new charm revision.


If neither 1 nor 2 is fulfilled, on the other hand, we'd bail out and do nothing.

**Comment by sed-i** [comment]
> check the git diff for the current commit

This won't work if the diff included a change in charmcraft.yaml's `parts` section:
https://discourse.charmhub.io/t/charm-packing-will-not-include-all-files-by-default-anymore/4924

**Comment by jnsgruk** [comment]
I think that's a pretty good start @simskij - parsing the primed files also shouldn't be a huge issue, but could be a change for later on.

**Comment by simskij** [comment]
> 

But then `charmcraft.yaml` will have changed. If the worry is about having **some** false positives, I'm completely fine with that short-term.

**Comment by sed-i** [comment]
@facundobatista is there an importable callable from charmcraft that could generate the list of files of a workdir that would go into a charm (excluding the venv)?

**Comment by facundobatista** [comment]
Hello! Currently `charmcraft` is not thought to be used as a library, but probably you could import modules from it and we can have some functionality isolated.

That said, I don't think that the purpose of this issue is a good idea. Having new revisions even if there is no "charm changes" is a very good idea some times, and for an important reason: security. 

If a security issue is fixed in any of the libraries used for your charm, you DO want a new revision, even if nothing changed in the charm.

I have a question for you: what is the problem you found in getting new revisions? Thanks!

**Comment by simskij** [comment]
> Hello! Currently `charmcraft` is not thought to be used as a library, but probably you could import modules from it and we can have some functionality isolated.
> 
> That said, I don't think that the purpose of this issue is a good idea. Having new revisions even if there is no "charm changes" is a very good idea some times, and for an important reason: security.
> 
> If a security issue is fixed in any of the libraries used for your charm, you DO want a new revision, even if nothing changed in the charm.
> 
> I have a question for you: what is the problem you found in getting new revisions? Thanks!

Personally, I don't mind too much. It will take quite a while until we overflow the counter, even if we were to put all our focus into just increasing it. 😅 

The biggest problem I envision is that it might give a false sense of progression to the users. Imagine if you deploy your charm, only to one week later notice that there have been 50 new revisions since. Should you upgrade? Should you not? 🤷🏼‍♂️ 

Building it, but not uploading it if the *.charm checksum is the same as the remote one would be one option, but would require **something** (charmcraft-cli would is a good candidate in my mind) to provide the checksum of the latest remote revision.

**Comment by DomFleischmann** [comment]
> The biggest problem I envision is that it might give a false sense of progression to the users. Imagine if you deploy your charm, only to one week later notice that there have been 50 new revisions since. Should you upgrade? Should you not? 🤷🏼‍♂️

With channels, revisions are really non indicative of any kind of progress in the charms, as the new 50 revisions could all have been fixes in different channels that don't apply to the user. I think we should really clarify that revisions are entirely decoupled from versioning and only serve as an identifier of a certain artifact in charmhub.

**Comment by simskij** [comment]
So our decision is to always re-upload, regardless of if the charm files have any delta?

I'm fine with that but would still like to suggest that @sergiusens and @facundobatista add to the charmcraft roadmap a way to compare the local .charm checksum with the one on charmhub.

**Comment by sergiusens** [comment]
This would need support from Charmhub (@noise) first, unless you are thinking of a client side comparison for which I don't know why one would need charmcraft for that. In Snap Store we have a dry run  option in the upload/push endpoint which helps with prechecks as some snaps can be rather large (although support for checksum is not supported).

@DomFleischmann is right as well, revisions are not versions, versions are the human way to communicate change.

In Charmcraft you can now use craftctl to set a version by running whatever you need to run to define the version.

**Comment by jnsgruk** [comment]
> Currently, there is no (documented) way to fetch a .charm file from Charmhub after it's been pushed using Charmcraft.

You can however do `juju download some-charm`, which might help:

```
❯ juju download --help
Usage: juju download [options] [options] <charm>

Summary:
Locates and then downloads a CharmHub charm.

Global Options:
--debug  (= false)
    equivalent to --show-log --logging-config=<root>=DEBUG
-h, --help  (= false)
    Show help on a command or other topic.
--logging-config (= "")
    specify log levels for modules
--quiet  (= false)
    show no informational output
--show-log  (= false)
    if set, write the log file to stderr
--verbose  (= false)
    show more verbose output

Command Options:
--arch (= "all")
    specify an arch <all|amd64|arm64|armhf|i386|ppc64el|s390x>
--channel (= "")
    specify a channel to use instead of the default release
--charmhub-url (= "https://api.charmhub.io")
    specify the Charmhub URL for querying the store
--filepath (= "")
    filepath location of the charm to download to
--no-progress  (= false)
    disable the progress bar
--series (= "all")
    specify a series

Details:
Download a charm to the current directory from the CharmHub store
by a specified name.

Adding a hyphen as the second argument allows the download to be piped
to stdout.

Examples:
    juju download postgresql
    juju download postgresql --no-progress - > postgresql.charm
```

**Comment by simskij** [comment]
> > Currently, there is no (documented) way to fetch a .charm file from Charmhub after it's been pushed using Charmcraft.
> 
> You can however do `juju download some-charm`, which might help:
> 
> ```
> ❯ juju download --help
> Usage: juju download [options] [options] <charm>
> 
> Summary:
> Locates and then downloads a CharmHub charm.
> 
> Global Options:
> --debug  (= false)
>     equivalent to --show-log --logging-config=<root>=DEBUG
> -h, --help  (= false)
>     Show help on a command or other topic.
> --logging-config (= "")
>     specify log levels for modules
> --quiet  (= false)
>     show no informational output
> --show-log  (= false)
>     if set, write the log file to stderr
> --verbose  (= false)
>     show more verbose output
> 
> Command Options:
> --arch (= "all")
>     specify an arch <all|amd64|arm64|armhf|i386|ppc64el|s390x>
> --channel (= "")
>     specify a channel to use instead of the default release
> --charmhub-url (= "https://api.charmhub.io")
>     specify the Charmhub URL for querying the store
> --filepath (= "")
>     filepath location of the charm to download to
> --no-progress  (= false)
>     disable the progress bar
> --series (= "all")
>     specify a series
> 
> Details:
> Download a charm to the current directory from the CharmHub store
> by a specified name.
> 
> Adding a hyphen as the second argument allows the download to be piped
> to stdout.
> 
> Examples:
>     juju download postgresql
>     juju download postgresql --no-progress - > postgresql.charm
> ```

That's excellent! TDIL!

**Comment by simskij** [comment]
We decided on a call not too long ago that we want to rebuild and publish the charm even when there are no changes to the actual charm code. The rationale behind this is that dependencies and underpinning OCI images might change independently of the charm code and that updating them would allow us to make sure the images would be patched with security fixes and such.
