### ISSUE TITLE
allow publish charm on feature branches

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/charming-actions#88]
https://github.com/canonical/charming-actions/blob/ee30262b8bdf2a7bc754802f6edc439eb60b12d0/dist/channel/index.js#L23192-L23207

if one works on a feature branch and wants to publish a charm, then the action will fail.
for example, I want to merge `feat-999-add-relation-psql` into `feat-999` branch, then action will fail because `Unhandled PR base name feat-999`

while would be good to publish charm (according to the internal logic) to `latest/edge/feat-999-add-relation-psql`

real use case: https://github.com/canonical/mlflow-operator/actions/runs/4344924048/jobs/7588922599

**Comment by ca-scribner** [comment]
I think the idea when written was that:
* `ch:latest/edge` is related to `gh:main`
* a PR from `gh:branch1` against `gh:main` logically then goes to `ch:latest/edge/branch1`
* a PR from `gh:branch1` against `gh:someOtherBranch` felt strange to put in `ch:latest/edge/branch1` because it wasn't related to `gh:main`
* it might make sense for a PR from `gh:branch1` against `gh:someOtherBranch` to publish to `ch:someOtherBranch/edge/branch1`, but that charmhub track often doesn't exist

But, I think @beliaev-maksim brings up a great point: it doesn't really matter what the target of the PR is - the source branch is what matters.  So just lumping them all in `ch:latest/edge/...` doesn't cause a problem

...technically maybe it could cause a problem in some edge case where a PR isn't rebased properly?  But that seems like something we shouldn't defend against

**Comment by ca-scribner** [comment]
While we're at it, we could I think get rid of all the logic around this channel choosing.  prs against `gh:track/*` can just get lumped into the same place, too
